# Generated by Django 3.1 on 2020-09-25 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_following'),
    ]

    operations = [
        migrations.RenameField(
            model_name='following',
            old_name='account',
            new_name='follower',
        ),
    ]
