# Generated by Django 3.1 on 2020-09-27 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_auto_20200925_0132'),
    ]

    operations = [
        migrations.DeleteModel(
            name='profile',
        ),
    ]
